### PR TITLE
Styled inbox messages count

### PR DESCRIPTION
**Pull request by bodrovis**
The result:

Styles are placed inline for simplicity, but it's adviced to move them into a proper .scss file.

### CODE REVIEW

**Comment by fredbonvalot** [comment]
NO, just change number pink and background white. it’s ok?

**Comment by bodrovis** [comment]
Done 


Border color can be added by typing `border-color: #000`

**Comment by fredbonvalot** [comment]
So good, i receive to email notification, but is it possible to change address no-reply@mailboxer in Pornaddict.fr ???

**Comment by bodrovis** [comment]
Sure, change this line https://github.com/bodrovis/app_xxx/blob/master/config/initializers/mailboxer.rb#L7 to anything you need

**Comment by fredbonvalot** [comment]
Ok sorry, very good thank you !

**Pull request merged**
