### PR TITLE
Fixes for mailboxer, some features are done

### PR DESCRIPTION
**Pull request by bodrovis**

### CODE REVIEW

**Comment by fredbonvalot** [comment]
Before accept the pull request, I see you change foreigner (1.7.4) and activerecord (>= 3.0.0) , it does not change and does not display the entries I have already registered in my admin ?

Sorry for my stupid question, I’m a dev junior !

**Comment by bodrovis** [comment]
@fredbonvalot That's a fair question. Foreigner is gone for good as it is already present in Rails 4. It was required by older version of Mailboxer, but as long as now we are using the latest one everything is okay. However, I really recommend quickly checking how conversations are working just in case.

**Comment by fredbonvalot** [comment]
> send a message 

STEP 1 : 
In ‘send message’ in (index/conversation ligne 9), I don’t want there are all users in a drop down menu ‘choose recipients’. I want there is only the user that I wrote. One or several according to my choice.




STEP 2 :
In ‘send message to user’ in (users/show ligne 74), I want that the user’s pseudo is directly wrote like recipient when I click on button ‘send message to user.pseudo’. 






> email’s notification  

For the email notification, I want that the users can disable the email notification directly on their profile. See like this exemple : 





> message notification

> the users should have a notification when they receive something, a little indicator on the conversation button which is situated in the navbar



Hope you understand me. Let me know when you can do that and if you have question.

For my part, I edit my Paypal. 

Thank’s again !

**Comment by bodrovis** [comment]
@fredbonvalot Regarding the first feature. Should it look like this (these data are fake of course):

**Comment by fredbonvalot** [comment]
Yes, it seems good !

**Comment by fredbonvalot** [comment]
There should also be a notification (navbar icon) when an answer is sent in conversation.


> message notification

> the users should have a notification when they receive something, a little indicator on the conversation button which is situated in the navbar

**Pull request merged**
